# Generated by Django 3.2.12 on 2022-04-17 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('to', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='project',
            field=models.ForeignKey(max_length=128, on_delete=django.db.models.deletion.CASCADE, to='to.project'),
        ),
    ]
